[account]
mnemonic = "shadow private easily thought say logic fault paddle word top book during ignore notable orange flight clock image wealth health outside kitten belt reform"
email = "test@example.com"
contributions = { total = 450.0, sbtc_share = 0.0 }